# Player knockout system configuration
knockout-threshold: 60          # Initial value from which knockout begins
heal-per-player-rate: 2         # Amount of extra seconds given
revive-threshold: 80            # Seconds required for revival
healing-range: 3.0              # Healing range from other players
lifting-range: 2.0              # Maximum distance (in blocks) from which a player can start lifting a knocked-out player

messages:
  message-prefix: "<gray>[<red>System</red>]</gray> "
  console-usage: "Only players can use this command!" # String
  not-knocked-out: "<red>You are not knocked out</red>"
  you-surrendered: "<red>You have surrendered</red>"
  no-knocked-out-nearby: "<red>There is no knocked out player nearby!</red>"
  you-are-knocked-out: "<red>You are knocked out and cannot lift other players!</red>"
  already-lifting: "<red>You are already lifting a player!</red>"
  player-lifted: "<green>You have lifted the player!</green>"
  healing-player: "<green>You are healing </green>"
  chat-prefix-knocked-out: "<red>☠</red><gray>[<dark_red>Knocked Out</dark_red>]<red>☠</red> "
  hologram-text: "<red>✚ Knocked Out ✚</red>"
  healed: "<green>You have been healed</green>"
  knocked-out-title: "<dark_red>You are knocked out</dark_red>"
  knocked-out-subtitle: "<gold>You have </gold>{seconds} seconds><gold> left</gold>"

